spring:
  cloud:
      gateway:
        filter:
          addUserId2HeaderFilter
        # ========== 2. 路由清单 ==========
        routes:
          - id: comment-route
            uri: lb://weblog-comment
            predicates:
              - Path=/weblog/article/comment/**
            filters:
              - StripPrefix=1
              - name: Retry
                args:
                  retries: 3
                  backoff:
                    firstBackoff: 50ms
                    maxBackoff: 500ms
          - id: static-route
            uri: http://static.xxx.com
            predicates:
              - Path=/static/**
          - id: sever-route             # 唯一即可
            uri: lb://weblog-service      # lb:// 代表从注册中心按服务名负载均衡
            predicates:
              - Path=/weblog/**          # 路径匹配
            filters:
              - StripPrefix=1          # 把 /user 这一段去掉再转发
              - name: Retry           # 重试3次（网络抖动神器）
                args:
                  retries: 3
                  backoff:
                    firstBackoff: 50ms
                    maxBackoff: 500ms


        # ========== 3. 跨域 ==========
        globalcors:
          cors-configurations:
            '[/**]': # 对哪些路径生效
              allowedOriginPatterns: "*"   # Spring Boot 2.4+ 推荐用 Patterns
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders: "*"
              allowCredentials: true
              maxAge: 3600
        # ========== 4. 统一超时 ==========
        httpclient:
          connect-timeout: 1000        # 建立连接超时
          response-timeout: 5s         # 读取响应超时（Spring Boot 3.x 官方推荐写法）
      nacos:
        config:
          server-addr: localhost:8848
          group: weblog
        discovery:
          service: weblog-gateway
          server-addr: localhost:8848
          port: 8080
          group: weblog
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
weblog:
  jwt:
    secret-key: weblog-secret-1221331232132133132132131321
    Ttl: 3600000 # 1 hour in milliseconds
    token-name: jwtToken
server:
  port: 8080