
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: Weblog-HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  sql:
    init:
      mode: always
      schema-locations: classpath*:db/init.sql
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    database: 0

Mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.disscheng.weblog.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
weblog:
  jwt:
    secret: ${Weblog.jwt.secret}
    Ttl: ${Weblog.jwt.Ttl}
    token-name: ${Weblog.jwt.token-name}
dubbo:
  application:
    name: weblog-comment
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
  config-center:
    address: nacos://localhost:8848
server:
  port: 8082