spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weblog?useSSL=false
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        group: weblog
      discovery:
        service: weblog-comment
        server-addr: localhost:8848
        port: 8082
        group: weblog

weblog:
  jwt:
    secret-key: weblog-secret-1221331232132133132132131321
    Ttl: 3600000 # 1 hour in milliseconds
    token-name: jwtToken

